[package]
name = "web_app"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.0"
diesel = {version = "1.4.8", features = ["postgres"]}
dotenv = "0.15.0"
rocket = "0.5.0-rc.1"
rocket_dyn_templates = {version = "0.1.0-rc.1", features = ["tera"]}
serde = "1.0.136"