[package]
name = "web_app"
version = "0.1.0"
edition = "2018"

[dependencies]
# tiberius = {version = "0.7.1", features = ["chrono"]}
# async-std = "1.10.0"
# chrono = "0.4"
anyhow = "1.0.0"
diesel = {version = "1.4.8", features = ["postgres"]}
dotenv = "0.15.0"