@startuml
left to right direction

map Games {
    id => UNIQUEIDENTIFIER
    Name => NVARCHAR(100)
    Genre => NVARCHAR(100)
    Release date => DATE
    Prime cost => MONEY
    Publisher_id => INT 
    Cost => MONEY
    Is_subscribable => BOOL
}

map Publishers {
    id => UNIQUEIDENTIFIER
    Name => NVARCHAR(100)
    Price => MONEY
    Popularity (0 to 10) => TINYINT
}

map Investors {
    id => UNIQUEIDENTIFIER
    Name => NVARCHAR(100)
    Is_company => BOOL
}

map Staff {
    id => UNIQUEIDENTIFIER
    Name => NVARCHAR(100)
    Birth => DATE
}

map Donations {
    id => UNIQUEIDENTIFIER
    User_id => INT
    Game_id => INT
    Amount => MONEY
    Donation_time => DATETIME
}

map Investors_Games {
    id => UNIQUEIDENTIFIER
    Investor_id => INT
    Game_id => INT
    Share => INT
    Invested => MONEY
}

map Jobs {
    id => UNIQUEIDENTIFIER
    Game_id => INT
    Staff_id => INT
    Position => NVARCHAR(100)
    First_working_day => DATE
    Last_working_day => DATE
    Salary => MONEY 
}

map Users {
    id => UNIQUEIDENTIFIER
    Nickname => NVARCHAR(100)
    Registration_date => DATE
}

Publishers::id --> Games::Publisher_id
Investors::id --> Investors_Games::Investor_id
Games::id --> Donations::Game_id
Games::id --> Investors_Games::Game_id
Games::id --> Jobs::Game_id
Staff::id --> Jobs::Staff_id
Donations::User_id <-- Users::id



@enduml