CREATE TABLE IF NOT EXISTS Publishers (
    ID SERIAL NOT NULL PRIMARY KEY, 
    Name VARCHAR(100) NOT NULL,
    Price MONEY NOT NULL, 
    Popularity SMALLINT NOT NULL CHECK(Popularity <= 10)
);

CREATE TABLE IF NOT EXISTS Games (
    ID SERIAL NOT NULL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Genre VARCHAR(100) NOT NULL, 
    Release_date DATE NOT NULL,
    Prime_cost MONEY NOT NULL, 
    Publisher_id INT REFERENCES Publishers(ID) ON DELETE CASCADE,
    Cost MONEY NOT NULL, 
    Is_subscribable BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS Staff (
    ID SERIAL NOT NULL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL, 
    Birth DATE NOT NULL 
);

CREATE TABLE IF NOT EXISTS Jobs (
    ID SERIAL NOT NULL PRIMARY KEY,
    Game_id INT REFERENCES Games(ID) ON DELETE CASCADE NOT NULL,
    Staff_id INT REFERENCES Staff(ID) ON DELETE CASCADE NOT NULL,
    Position VARCHAR(100) NOT NULL,
    First_work_day DATE NOT NULL,
    Last_work_day DATE,
    Salary MONEY NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    ID SERIAL NOT NULL PRIMARY KEY,
    Nickname VARCHAR(100) NOT NULL,
    Registration_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Donations (
    ID SERIAL NOT NULL PRIMARY KEY,
    User_id INT NOT NULL REFERENCES Users(ID) ON DELETE CASCADE,
    Game_id INT NOT NULL REFERENCES Games(ID) ON DELETE CASCADE,
    Amount MONEY NOT NULL,
    Donation_time TIMESTAMP NOT NULL 
);

CREATE TABLE IF NOT EXISTS Investors (
    ID SERIAL NOT NULL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Is_company BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS Investors_Games (
    ID SERIAL NOT NULL PRIMARY KEY,
    Investor_id INT REFERENCES Investors(ID) ON DELETE CASCADE NOT NULL,
    Game_id INT REFERENCES Games(ID) ON DELETE CASCADE NOT NULL,
    Share SMALLINT NOT NULL CHECK(Share <= 100),
    Invested MONEY NOT NULL 
);
