USE GameStudio
GO


DROP TABLE IF EXISTS Investor_Game
DROP TABLE IF EXISTS Donations
DROP TABLE IF EXISTS Jobs
DROP TABLE IF EXISTS Investors
DROP TABLE IF EXISTS Games
DROP TABLE IF EXISTS Staff
DROP TABLE IF EXISTS Publishers
GO

CREATE TABLE Publishers (
    ID INT NOT NULL PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Price MONEY NOT NULL, 
    Popularity TINYINT NOT NULL CHECK(Popularity <= 10)
);
GO

CREATE TABLE Games (
    ID INT NOT NULL PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Genre NVARCHAR(100) NOT NULL, 
    Release_date DATE NOT NULL,
    Prime_cost MONEY NOT NULL, 
    Publisher_id INT FOREIGN KEY REFERENCES Publishers(ID) ON DELETE CASCADE,
    Cost MONEY NOT NULL, 
    Is_Subscribable BIT NOT NULL DEFAULT 0
)
GO

CREATE TABLE Staff (
    ID INT NOT NULL PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL, 
    Birth DATE NOT NULL 
)
GO

CREATE TABLE Jobs (
    ID INT NOT NULL PRIMARY KEY IDENTITY,
    Game_id INT FOREIGN KEY REFERENCES Games(ID) ON DELETE CASCADE NOT NULL,
    Staff_id INT FOREIGN KEY REFERENCES Staff(ID) ON DELETE CASCADE NOT NULL,
    Position NVARCHAR(100) NOT NULL,
    First_Work_Day DATE NOT NULL,
    Last_Work_Day DATE,
    Salary MONEY NOT NULL
)
GO

CREATE TABLE Donations (
    ID INT NOT NULL PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Game_id INT NOT NULL FOREIGN KEY REFERENCES Games(ID) ON DELETE CASCADE,
    Total_Amount MONEY NOT NULL 
)
GO

CREATE TABLE Investors (
    ID INT NOT NULL PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Is_Company BIT NOT NULL DEFAULT 0
)
GO

CREATE TABLE Investor_Game (
    ID INT NOT NULL PRIMARY KEY IDENTITY,
    Investor_id INT FOREIGN KEY REFERENCES Investors(ID) NOT NULL,
    Game_id INT FOREIGN KEY REFERENCES Games(ID) NOT NULL,
    Share TINYINT NOT NULL CHECK(Share <= 100),
    Invested MONEY NOT NULL 
)
GO
